name: Deploy Backend to Render

on:
  push:
    branches: [ master, main ]
    paths:
      - 'python-backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render Deploy
        run: |
          echo "🚀 Deployment triggered via GitHub push"
          echo "Render will auto-deploy from this commit"
          echo "Check: https://dashboard.render.com/"
